name: main
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-18.04

        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_WEBHOOK_URL }}

        services:
            mariadb:
                image: mariadb:10.3
                ports:
                    - 3306:3306
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: dilps
                options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=5

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  coverage: pcov
                  tools: cs2pr
                  extensions: imagick

            - uses: actions/cache@v2
              with:
                  path: ~/.cache/composer
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - uses: actions/cache@v2
              with:
                  path: ~/.cache/yarn
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Setup problem matchers for PHP
              run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

            - name: Setup problem matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Prepare app
              id: app-setup
              run: |
                  mysql --protocol=tcp --user=root --execute='SET GLOBAL sql_mode = "";'
                  cp env.example .env
                  cp config/autoload/local.php.dist config/autoload/local.php

            - name: Build app
              id: app-build
              run: ./bin/build.sh

            - name: Load test data
              id: app-load-data
              run: ./bin/load-test-data.php

            - name: PHP CS Fixer
              id: app-php-fixer
              run: ./vendor/bin/php-cs-fixer fix --format=checkstyle | cs2pr

            - name: Yarn lint
              id: app-yarn-lint
              run: yarn lint

            - name: Prettier
              id: app-prettier
              run: ./node_modules/.bin/prettier --check .

            - name: Test PHP
              id: app-test-php
              run: ./vendor/bin/phpunit --coverage-clover coverage-clover.xml

            - name: Test Angular
              id: app-test-ng
              run: ./node_modules/.bin/ng test --progress false --watch=false --browsers ChromeHeadlessCustom

            - name: Upload code coverage
              id: app-upload-coverage
              run: |
                  curl -LO https://scrutinizer-ci.com/ocular.phar
                  php ocular.phar code-coverage:upload --format=php-clover coverage-clover.xml

            - uses: act10ns/slack@v1
              with:
                  status: ${{ job.status }}
                  steps: ${{ toJson(steps) }}
                  channel: '#-bot-ci'
              if: always()
